spring:
  datasource:
    url: 'ENC(1HCKsbVZGPHdG7yJCAbhfqD19yfFzOuplfI4IBW79vRG+n7w6/Mynfa8qtL33a/42WcCGVC0PEYA3lvzb97N49m9gjkZiWeHsQd2ncfhVID3/+oCi3B72oit7HZiug6nDQHmBEtzJ0+BO+SKLGkSxkNLxR6NN9ouRPFzyqzvxL2jkUhYMF7Vf+uT6k2QhJIeNdSv8S6SsUq+Z4v9uCKhSYlIwiurh6/UVwl9E3BDE1s=)'
    username: 'ENC(6AogQsJmwjHYwYKvlubtYk3i6QYrl507)'
    password: 'ENC(iIo8nIJZagvEldC/o3bhnOE26G0p9l6S2GabQuVotDajqZpxKZwA9g==)'
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_uuid
      logic-delete-field: isDeleted
      logic-delete-value: true
      logic-not-delete-value: false

logging:
  level:
    root: WARN
    io.github.timemachinelab: INFO
    com.baomidou.mybatisplus: WARN

aether:
  console:
    session-auth:
      user-id: 'ENC(KK6klTq56ESUZAARF6fz8odrAtwb1Yp7GJXkBTko22g=)'
      login-name: 'ENC(QVqXO9aWFlBtlDowf7i2koCYwnOOuhpA5JT18BTr2PE=)'
      password: 'ENC(j3LOSrQBkQ4zgnlZWBzbvUdNKYcF/JdJ/FuXmCN6cWUQxvIXEWuZgHqqCtGdSV1i)'
      display-name: 'ENC(VgNfun4JpBufA7Wv4Sxmn6h68eL4alqM2sf9ZZEP+Cc=)'
      email: 'ENC(FUGKdyVhklhVYiAt8t6JpsLpgyb1jgn5GEmFlnYK4ys=)'
      role: 'ENC(PiIoH5E5sQS3nhF7CAR+Bg==)'
      token-secret: 'ENC(048VjhmuI9iRWYpehkSn92n5d+damCmbgax/FUa9FgcYAq5GVKVkXfSC6Qqj8IBOPBHQCH+omMuzPmuROty9oA==)'
      token-ttl-seconds: ${AETHER_CONSOLE_AUTH_TOKEN_TTL_SECONDS:43200}
